//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace client_yeni.com.basaktelemetri {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback plakalarOperationCompleted;
        
        private System.Threading.SendOrPostCallback sorguOperationCompleted;
        
        private System.Threading.SendOrPostCallback smilasyonOperationCompleted;
        
        private System.Threading.SendOrPostCallback smilasyon_atlamaliOperationCompleted;
        
        private System.Threading.SendOrPostCallback plakalar_FORM2OperationCompleted;
        
        private System.Threading.SendOrPostCallback sorgu_hiz_kucuk_FORM2OperationCompleted;
        
        private System.Threading.SendOrPostCallback sorgu_hiz_buyuk_FORM2OperationCompleted;
        
        private System.Threading.SendOrPostCallback sorgu_yer_FORM2OperationCompleted;
        
        private System.Threading.SendOrPostCallback istatistik_FORM2OperationCompleted;
        
        private System.Threading.SendOrPostCallback neredeydim_FORM2OperationCompleted;
        
        private System.Threading.SendOrPostCallback yedekle_FORM2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::client_yeni.Properties.Settings.Default.client_yeni_com_basaktelemetri_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event plakalarCompletedEventHandler plakalarCompleted;
        
        /// <remarks/>
        public event sorguCompletedEventHandler sorguCompleted;
        
        /// <remarks/>
        public event smilasyonCompletedEventHandler smilasyonCompleted;
        
        /// <remarks/>
        public event smilasyon_atlamaliCompletedEventHandler smilasyon_atlamaliCompleted;
        
        /// <remarks/>
        public event plakalar_FORM2CompletedEventHandler plakalar_FORM2Completed;
        
        /// <remarks/>
        public event sorgu_hiz_kucuk_FORM2CompletedEventHandler sorgu_hiz_kucuk_FORM2Completed;
        
        /// <remarks/>
        public event sorgu_hiz_buyuk_FORM2CompletedEventHandler sorgu_hiz_buyuk_FORM2Completed;
        
        /// <remarks/>
        public event sorgu_yer_FORM2CompletedEventHandler sorgu_yer_FORM2Completed;
        
        /// <remarks/>
        public event istatistik_FORM2CompletedEventHandler istatistik_FORM2Completed;
        
        /// <remarks/>
        public event neredeydim_FORM2CompletedEventHandler neredeydim_FORM2Completed;
        
        /// <remarks/>
        public event yedekle_FORM2CompletedEventHandler yedekle_FORM2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string login(string sirket, string kullanici, string sifre) {
            object[] results = this.Invoke("login", new object[] {
                        sirket,
                        kullanici,
                        sifre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string sirket, string kullanici, string sifre) {
            this.loginAsync(sirket, kullanici, sifre, null);
        }
        
        /// <remarks/>
        public void loginAsync(string sirket, string kullanici, string sifre, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        sirket,
                        kullanici,
                        sifre}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/plakalar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Track_PortPlaka[] plakalar(string port) {
            object[] results = this.Invoke("plakalar", new object[] {
                        port});
            return ((Track_PortPlaka[])(results[0]));
        }
        
        /// <remarks/>
        public void plakalarAsync(string port) {
            this.plakalarAsync(port, null);
        }
        
        /// <remarks/>
        public void plakalarAsync(string port, object userState) {
            if ((this.plakalarOperationCompleted == null)) {
                this.plakalarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnplakalarOperationCompleted);
            }
            this.InvokeAsync("plakalar", new object[] {
                        port}, this.plakalarOperationCompleted, userState);
        }
        
        private void OnplakalarOperationCompleted(object arg) {
            if ((this.plakalarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.plakalarCompleted(this, new plakalarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sorgu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] sorgu(string plaka) {
            object[] results = this.Invoke("sorgu", new object[] {
                        plaka});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void sorguAsync(string plaka) {
            this.sorguAsync(plaka, null);
        }
        
        /// <remarks/>
        public void sorguAsync(string plaka, object userState) {
            if ((this.sorguOperationCompleted == null)) {
                this.sorguOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsorguOperationCompleted);
            }
            this.InvokeAsync("sorgu", new object[] {
                        plaka}, this.sorguOperationCompleted, userState);
        }
        
        private void OnsorguOperationCompleted(object arg) {
            if ((this.sorguCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sorguCompleted(this, new sorguCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/smilasyon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Track_LocationInf[] smilasyon(string plaka, System.DateTime date, System.DateTime date2) {
            object[] results = this.Invoke("smilasyon", new object[] {
                        plaka,
                        date,
                        date2});
            return ((Track_LocationInf[])(results[0]));
        }
        
        /// <remarks/>
        public void smilasyonAsync(string plaka, System.DateTime date, System.DateTime date2) {
            this.smilasyonAsync(plaka, date, date2, null);
        }
        
        /// <remarks/>
        public void smilasyonAsync(string plaka, System.DateTime date, System.DateTime date2, object userState) {
            if ((this.smilasyonOperationCompleted == null)) {
                this.smilasyonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsmilasyonOperationCompleted);
            }
            this.InvokeAsync("smilasyon", new object[] {
                        plaka,
                        date,
                        date2}, this.smilasyonOperationCompleted, userState);
        }
        
        private void OnsmilasyonOperationCompleted(object arg) {
            if ((this.smilasyonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.smilasyonCompleted(this, new smilasyonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/smilasyon_atlamali", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Track_LocationInf[] smilasyon_atlamali(string plaka, System.DateTime date, System.DateTime date2, int atlama) {
            object[] results = this.Invoke("smilasyon_atlamali", new object[] {
                        plaka,
                        date,
                        date2,
                        atlama});
            return ((Track_LocationInf[])(results[0]));
        }
        
        /// <remarks/>
        public void smilasyon_atlamaliAsync(string plaka, System.DateTime date, System.DateTime date2, int atlama) {
            this.smilasyon_atlamaliAsync(plaka, date, date2, atlama, null);
        }
        
        /// <remarks/>
        public void smilasyon_atlamaliAsync(string plaka, System.DateTime date, System.DateTime date2, int atlama, object userState) {
            if ((this.smilasyon_atlamaliOperationCompleted == null)) {
                this.smilasyon_atlamaliOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsmilasyon_atlamaliOperationCompleted);
            }
            this.InvokeAsync("smilasyon_atlamali", new object[] {
                        plaka,
                        date,
                        date2,
                        atlama}, this.smilasyon_atlamaliOperationCompleted, userState);
        }
        
        private void Onsmilasyon_atlamaliOperationCompleted(object arg) {
            if ((this.smilasyon_atlamaliCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.smilasyon_atlamaliCompleted(this, new smilasyon_atlamaliCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/plakalar_FORM2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Track_LocationInf[] plakalar_FORM2(string plaka, System.DateTime date, System.DateTime date2) {
            object[] results = this.Invoke("plakalar_FORM2", new object[] {
                        plaka,
                        date,
                        date2});
            return ((Track_LocationInf[])(results[0]));
        }
        
        /// <remarks/>
        public void plakalar_FORM2Async(string plaka, System.DateTime date, System.DateTime date2) {
            this.plakalar_FORM2Async(plaka, date, date2, null);
        }
        
        /// <remarks/>
        public void plakalar_FORM2Async(string plaka, System.DateTime date, System.DateTime date2, object userState) {
            if ((this.plakalar_FORM2OperationCompleted == null)) {
                this.plakalar_FORM2OperationCompleted = new System.Threading.SendOrPostCallback(this.Onplakalar_FORM2OperationCompleted);
            }
            this.InvokeAsync("plakalar_FORM2", new object[] {
                        plaka,
                        date,
                        date2}, this.plakalar_FORM2OperationCompleted, userState);
        }
        
        private void Onplakalar_FORM2OperationCompleted(object arg) {
            if ((this.plakalar_FORM2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.plakalar_FORM2Completed(this, new plakalar_FORM2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sorgu_hiz_kucuk_FORM2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] sorgu_hiz_kucuk_FORM2(string plaka, System.DateTime date, System.DateTime date2, double speed) {
            object[] results = this.Invoke("sorgu_hiz_kucuk_FORM2", new object[] {
                        plaka,
                        date,
                        date2,
                        speed});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void sorgu_hiz_kucuk_FORM2Async(string plaka, System.DateTime date, System.DateTime date2, double speed) {
            this.sorgu_hiz_kucuk_FORM2Async(plaka, date, date2, speed, null);
        }
        
        /// <remarks/>
        public void sorgu_hiz_kucuk_FORM2Async(string plaka, System.DateTime date, System.DateTime date2, double speed, object userState) {
            if ((this.sorgu_hiz_kucuk_FORM2OperationCompleted == null)) {
                this.sorgu_hiz_kucuk_FORM2OperationCompleted = new System.Threading.SendOrPostCallback(this.Onsorgu_hiz_kucuk_FORM2OperationCompleted);
            }
            this.InvokeAsync("sorgu_hiz_kucuk_FORM2", new object[] {
                        plaka,
                        date,
                        date2,
                        speed}, this.sorgu_hiz_kucuk_FORM2OperationCompleted, userState);
        }
        
        private void Onsorgu_hiz_kucuk_FORM2OperationCompleted(object arg) {
            if ((this.sorgu_hiz_kucuk_FORM2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sorgu_hiz_kucuk_FORM2Completed(this, new sorgu_hiz_kucuk_FORM2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sorgu_hiz_buyuk_FORM2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] sorgu_hiz_buyuk_FORM2(string plaka, System.DateTime date, System.DateTime date2, double speed) {
            object[] results = this.Invoke("sorgu_hiz_buyuk_FORM2", new object[] {
                        plaka,
                        date,
                        date2,
                        speed});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void sorgu_hiz_buyuk_FORM2Async(string plaka, System.DateTime date, System.DateTime date2, double speed) {
            this.sorgu_hiz_buyuk_FORM2Async(plaka, date, date2, speed, null);
        }
        
        /// <remarks/>
        public void sorgu_hiz_buyuk_FORM2Async(string plaka, System.DateTime date, System.DateTime date2, double speed, object userState) {
            if ((this.sorgu_hiz_buyuk_FORM2OperationCompleted == null)) {
                this.sorgu_hiz_buyuk_FORM2OperationCompleted = new System.Threading.SendOrPostCallback(this.Onsorgu_hiz_buyuk_FORM2OperationCompleted);
            }
            this.InvokeAsync("sorgu_hiz_buyuk_FORM2", new object[] {
                        plaka,
                        date,
                        date2,
                        speed}, this.sorgu_hiz_buyuk_FORM2OperationCompleted, userState);
        }
        
        private void Onsorgu_hiz_buyuk_FORM2OperationCompleted(object arg) {
            if ((this.sorgu_hiz_buyuk_FORM2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sorgu_hiz_buyuk_FORM2Completed(this, new sorgu_hiz_buyuk_FORM2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sorgu_yer_FORM2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] sorgu_yer_FORM2(string plaka) {
            object[] results = this.Invoke("sorgu_yer_FORM2", new object[] {
                        plaka});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void sorgu_yer_FORM2Async(string plaka) {
            this.sorgu_yer_FORM2Async(plaka, null);
        }
        
        /// <remarks/>
        public void sorgu_yer_FORM2Async(string plaka, object userState) {
            if ((this.sorgu_yer_FORM2OperationCompleted == null)) {
                this.sorgu_yer_FORM2OperationCompleted = new System.Threading.SendOrPostCallback(this.Onsorgu_yer_FORM2OperationCompleted);
            }
            this.InvokeAsync("sorgu_yer_FORM2", new object[] {
                        plaka}, this.sorgu_yer_FORM2OperationCompleted, userState);
        }
        
        private void Onsorgu_yer_FORM2OperationCompleted(object arg) {
            if ((this.sorgu_yer_FORM2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sorgu_yer_FORM2Completed(this, new sorgu_yer_FORM2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/istatistik_FORM2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Track_LocationInf[] istatistik_FORM2(string plaka, System.DateTime date, System.DateTime date2) {
            object[] results = this.Invoke("istatistik_FORM2", new object[] {
                        plaka,
                        date,
                        date2});
            return ((Track_LocationInf[])(results[0]));
        }
        
        /// <remarks/>
        public void istatistik_FORM2Async(string plaka, System.DateTime date, System.DateTime date2) {
            this.istatistik_FORM2Async(plaka, date, date2, null);
        }
        
        /// <remarks/>
        public void istatistik_FORM2Async(string plaka, System.DateTime date, System.DateTime date2, object userState) {
            if ((this.istatistik_FORM2OperationCompleted == null)) {
                this.istatistik_FORM2OperationCompleted = new System.Threading.SendOrPostCallback(this.Onistatistik_FORM2OperationCompleted);
            }
            this.InvokeAsync("istatistik_FORM2", new object[] {
                        plaka,
                        date,
                        date2}, this.istatistik_FORM2OperationCompleted, userState);
        }
        
        private void Onistatistik_FORM2OperationCompleted(object arg) {
            if ((this.istatistik_FORM2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.istatistik_FORM2Completed(this, new istatistik_FORM2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/neredeydim_FORM2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] neredeydim_FORM2(string plaka, System.DateTime date) {
            object[] results = this.Invoke("neredeydim_FORM2", new object[] {
                        plaka,
                        date});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void neredeydim_FORM2Async(string plaka, System.DateTime date) {
            this.neredeydim_FORM2Async(plaka, date, null);
        }
        
        /// <remarks/>
        public void neredeydim_FORM2Async(string plaka, System.DateTime date, object userState) {
            if ((this.neredeydim_FORM2OperationCompleted == null)) {
                this.neredeydim_FORM2OperationCompleted = new System.Threading.SendOrPostCallback(this.Onneredeydim_FORM2OperationCompleted);
            }
            this.InvokeAsync("neredeydim_FORM2", new object[] {
                        plaka,
                        date}, this.neredeydim_FORM2OperationCompleted, userState);
        }
        
        private void Onneredeydim_FORM2OperationCompleted(object arg) {
            if ((this.neredeydim_FORM2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.neredeydim_FORM2Completed(this, new neredeydim_FORM2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/yedekle_FORM2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Track_LocationInf[] yedekle_FORM2(System.DateTime date, System.DateTime date2) {
            object[] results = this.Invoke("yedekle_FORM2", new object[] {
                        date,
                        date2});
            return ((Track_LocationInf[])(results[0]));
        }
        
        /// <remarks/>
        public void yedekle_FORM2Async(System.DateTime date, System.DateTime date2) {
            this.yedekle_FORM2Async(date, date2, null);
        }
        
        /// <remarks/>
        public void yedekle_FORM2Async(System.DateTime date, System.DateTime date2, object userState) {
            if ((this.yedekle_FORM2OperationCompleted == null)) {
                this.yedekle_FORM2OperationCompleted = new System.Threading.SendOrPostCallback(this.Onyedekle_FORM2OperationCompleted);
            }
            this.InvokeAsync("yedekle_FORM2", new object[] {
                        date,
                        date2}, this.yedekle_FORM2OperationCompleted, userState);
        }
        
        private void Onyedekle_FORM2OperationCompleted(object arg) {
            if ((this.yedekle_FORM2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.yedekle_FORM2Completed(this, new yedekle_FORM2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Track_PortPlaka {
        
        private int plakaIDField;
        
        private string portNumberField;
        
        private string plakaField;
        
        /// <remarks/>
        public int PlakaID {
            get {
                return this.plakaIDField;
            }
            set {
                this.plakaIDField = value;
            }
        }
        
        /// <remarks/>
        public string PortNumber {
            get {
                return this.portNumberField;
            }
            set {
                this.portNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Plaka {
            get {
                return this.plakaField;
            }
            set {
                this.plakaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Track_LocationInf {
        
        private int locationInfField;
        
        private string portNumberField;
        
        private string plakaField;
        
        private string latitudeField;
        
        private string latPosField;
        
        private string longitudeField;
        
        private string lonPosField;
        
        private string speedField;
        
        private string courseField;
        
        private string emergencyCallField;
        
        private string contactField;
        
        private System.DateTime dateTimeField;
        
        /// <remarks/>
        public int LocationInf {
            get {
                return this.locationInfField;
            }
            set {
                this.locationInfField = value;
            }
        }
        
        /// <remarks/>
        public string PortNumber {
            get {
                return this.portNumberField;
            }
            set {
                this.portNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Plaka {
            get {
                return this.plakaField;
            }
            set {
                this.plakaField = value;
            }
        }
        
        /// <remarks/>
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public string LatPos {
            get {
                return this.latPosField;
            }
            set {
                this.latPosField = value;
            }
        }
        
        /// <remarks/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string LonPos {
            get {
                return this.lonPosField;
            }
            set {
                this.lonPosField = value;
            }
        }
        
        /// <remarks/>
        public string Speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        public string Course {
            get {
                return this.courseField;
            }
            set {
                this.courseField = value;
            }
        }
        
        /// <remarks/>
        public string EmergencyCall {
            get {
                return this.emergencyCallField;
            }
            set {
                this.emergencyCallField = value;
            }
        }
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void plakalarCompletedEventHandler(object sender, plakalarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class plakalarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal plakalarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Track_PortPlaka[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Track_PortPlaka[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void sorguCompletedEventHandler(object sender, sorguCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sorguCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sorguCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void smilasyonCompletedEventHandler(object sender, smilasyonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class smilasyonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal smilasyonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Track_LocationInf[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Track_LocationInf[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void smilasyon_atlamaliCompletedEventHandler(object sender, smilasyon_atlamaliCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class smilasyon_atlamaliCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal smilasyon_atlamaliCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Track_LocationInf[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Track_LocationInf[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void plakalar_FORM2CompletedEventHandler(object sender, plakalar_FORM2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class plakalar_FORM2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal plakalar_FORM2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Track_LocationInf[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Track_LocationInf[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void sorgu_hiz_kucuk_FORM2CompletedEventHandler(object sender, sorgu_hiz_kucuk_FORM2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sorgu_hiz_kucuk_FORM2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sorgu_hiz_kucuk_FORM2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void sorgu_hiz_buyuk_FORM2CompletedEventHandler(object sender, sorgu_hiz_buyuk_FORM2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sorgu_hiz_buyuk_FORM2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sorgu_hiz_buyuk_FORM2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void sorgu_yer_FORM2CompletedEventHandler(object sender, sorgu_yer_FORM2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sorgu_yer_FORM2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sorgu_yer_FORM2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void istatistik_FORM2CompletedEventHandler(object sender, istatistik_FORM2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class istatistik_FORM2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal istatistik_FORM2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Track_LocationInf[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Track_LocationInf[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void neredeydim_FORM2CompletedEventHandler(object sender, neredeydim_FORM2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class neredeydim_FORM2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal neredeydim_FORM2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void yedekle_FORM2CompletedEventHandler(object sender, yedekle_FORM2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class yedekle_FORM2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal yedekle_FORM2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Track_LocationInf[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Track_LocationInf[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591