//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client_yeni.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=78.189.180.167;Initial Catalog=Track_EmergencyCall_Contact;Persist Se" +
            "curity Info=True;User ID=coskunkazma;Password=25karasahin")]
        public string Track_EmergencyCall_ContactConnectionString {
            get {
                return ((string)(this["Track_EmergencyCall_ContactConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.2;Initial Catalog=Track_EmergencyCall_Contact;Persist Secur" +
            "ity Info=True;User ID=coskunkazma;Password=25karasahin")]
        public string Track_EmergencyCall_ContactConnectionString1 {
            get {
                return ((string)(this["Track_EmergencyCall_ContactConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=78.189.180.28;Initial Catalog=Track_EmergencyCall_Contact;Persist Sec" +
            "urity Info=True;User ID=coskunkazma;Password=25karasahin")]
        public string Track_EmergencyCall_ContactConnectionString2 {
            get {
                return ((string)(this["Track_EmergencyCall_ContactConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\Database2.sdf")]
        public string Database2ConnectionString {
            get {
                return ((string)(this["Database2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\Local.mdf;Integrated Se" +
            "curity=True;User Instance=True")]
        public string LocalConnectionString {
            get {
                return ((string)(this["LocalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COSKUN-PC\\COSKUN;Initial Catalog=Track_EmergencyCall_Contact;User ID=" +
            "sa;Password=kartal25")]
        public string Track_EmergencyCall_ContactConnectionString3 {
            get {
                return ((string)(this["Track_EmergencyCall_ContactConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COSKUN-PC\\COSKUN;Initial Catalog=Track_EmergencyCall_Contact;Integrat" +
            "ed Security=True")]
        public string Track_EmergencyCall_ContactConnectionString4 {
            get {
                return ((string)(this["Track_EmergencyCall_ContactConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.2;Initial Catalog=Track_EmergencyCall_Contact;Persist Secur" +
            "ity Info=True;User ID=coskunkazma;Password=kartal25")]
        public string Track_EmergencyCall_ContactConnectionString5 {
            get {
                return ((string)(this["Track_EmergencyCall_ContactConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=78.189.180.28;Initial Catalog=Track_EmergencyCall_Contact;Persist Sec" +
            "urity Info=True;User ID=coskunkazma;Password=kartal25")]
        public string Track_EmergencyCall_ContactConnectionString6 {
            get {
                return ((string)(this["Track_EmergencyCall_ContactConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.70;Initial Catalog=Track_EmergencyCall_Contact;Persist Secu" +
            "rity Info=True;User ID=coskunkazma;Password=kartal25")]
        public string Track_EmergencyCall_ContactConnectionString7 {
            get {
                return ((string)(this["Track_EmergencyCall_ContactConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=127.0.0.1;Initial Catalog=Local_veriler;Integrated Security=True")]
        public string Local_verilerConnectionString {
            get {
                return ((string)(this["Local_verilerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://basaktelemetri.com/locationWebService.asmx")]
        public string client_yeni_com_basaktelemetri_Service1 {
            get {
                return ((string)(this["client_yeni_com_basaktelemetri_Service1"]));
            }
        }
    }
}
